name: Squash history
on:
    schedule:
      - cron: "0 0/6 * * *"
    workflow_dispatch:
jobs:
    update:
        permissions:
            contents: write
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                git config --global user.name "${{ github.actor }}"
                git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                git reset $(git commit-tree HEAD^{tree} -m "Squash")
                git push --force
