name: Update block lists
on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
    update:
        permissions:
            contents: write
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                cache: 'npm'
                node-version: '22'
            - run: npm ci
            - run: npm run update
            - run: |
                # configure user
                git config --global user.name "${{ github.actor }}"
                git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            
                # stage any file changes to be committed
                git add .
            
                # make commit with staged changes
                git commit -m 'update list'
            
                # push the commit back up to source GitHub repository
                git push
